# Generated by Django 3.0 on 2020-01-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='blood',
            field=models.CharField(default='o+', max_length=5),
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(default='Trainer', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='jdate',
            field=models.DateField(default='2019-08-01'),
        ),
    ]
