# Generated by Django 3.0 on 2020-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admapp', '0002_auto_20200113_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood',
            field=models.CharField(default='o+', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(default='B. Tech', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default='Hindu', max_length=10),
        ),
    ]
