# Generated by Django 3.0 on 2020-01-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admapp', '0004_remove_student_guardian'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ltype', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
