# Generated by Django 3.0 on 2020-01-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admapp', '0006_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('asno', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('mark1', models.IntegerField()),
                ('mark2', models.IntegerField()),
                ('mark3', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
