# Generated by Django 3.0 on 2020-01-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admapp', '0007_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status1', models.CharField(max_length=10)),
                ('status2', models.CharField(max_length=10)),
                ('status3', models.CharField(max_length=10)),
                ('status4', models.CharField(max_length=10)),
            ],
        ),
    ]
